### ISSUE TITLE
windows not resized in mobile version 

### ISSUE THREAD

**Issue by bcclsn** [xunil75/PyPlex#8]
as you can see in this screen: 
https://mega.nz/#!zYECiRRJ!OolHZnLfnm03xCgQ0hxy2rL65jNl5N71um6MLzEtZNc
in mobile version, if the download's title name is too long, the gui is non resized correctly.

please, fix it if you can, or fix it in your next theme PyWhite.

alex

**Comment by dogb82** [comment]
Hi Alex
Thank you for your comment. Can you send more information about your device (like mobile device model/screen size/screen resolution), that i can reproduce it. When i reproduce it, i can find the cause better.
Thanks.
Regards.

**Comment by bcclsn** [comment]
hi marco :)

I have a honor 8 with android 7.0 stock (no root) and I'm using firefox 59.0.2 :)
display: 1080x1920, 5.2", 424 ppi

thanks in advance,
alex

**Comment by dogb82** [comment]
Hi Alex
This Bug is fixed. It would be nice when you can check it also. It was difficult to reproduce it. 
Thx.
Regards,
Dog

**Comment by bcclsn** [comment]
bug fixed, thank you so much :)

alex

edit. nope, it isn't fixed :(

**Comment by xunil75** [comment]
Hi Alex, have you downloaded the Theme or the modified files again? Can you post again a screenshot of your Problem?

**Comment by bcclsn** [comment]
hi marco, I'm sorry!
I've re-updated the files and now it works! 

bug fixed :)
